name: List repository files
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    list-files:
        runs-on: ubuntu-latest
        steps:
            - name: list all files and folders
              run: |
                echo "repo contents:"
                ls -R
                pwd