name: run commands
on: 
  workflow_dispatch:
jobs:
    clone-my-repo:
        runs-on: ubuntu_latest
        steps:
            -uses: actions/checkout@V4
            -run: ls -lrt
            -run: pwd && ls -a
            -run: echo "Hello Shruti"
