name: run commands
on: 
  workflow_dispatch:
jobs:
    clone-my-repo:
        runs_on: ubuntu-latest
        steps:
            -uses: actions/checkout@V3
            -run: ls -lrt
            -run: pwd && ls -a
            -run: echo "Hello Shruti"
